"""init tables_2

Revision ID: 3853cbf08ade
Revises: f300f11ae4f9
Create Date: 2026-07-09 03:01:07.152770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3853cbf08ade'
down_revision: Union[str, None] = 'f300f11ae4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remark_email'), 'remark', ['email'], unique=True)
    op.create_index(op.f('ix_remark_id'), 'remark', ['id'], unique=False)
    op.create_index(op.f('ix_remark_username'), 'remark', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remark_username'), table_name='remark')
    op.drop_index(op.f('ix_remark_id'), table_name='remark')
    op.drop_index(op.f('ix_remark_email'), table_name='remark')
    op.drop_table('remark')
    # ### end Alembic commands ###
