"""add reserved_order_id to user_coupons

Revision ID: 70991b24d1f9
Revises: 4d168641cc8a
Create Date: 2026-07-10 06:13:36.497961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70991b24d1f9'
down_revision: Union[str, None] = '4d168641cc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_coupons', sa.Column('reserved_order_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_coupons', 'reserved_order_id')
    # ### end Alembic commands ###
